# Generated by Django 6.0.7 on 2026-07-25 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("personal-accident", "Personal Accident"),
                            ("health", "Health"),
                            ("life", "Life"),
                        ],
                        max_length=50,
                    ),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cover", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("QUOTED", "Quoted"),
                            ("ACTIVE", "Active"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "db_table": "policies",
            },
        ),
    ]
