# Generated by Django 6.0.7 on 2026-07-25 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_state",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("new_state", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="policies.policy",
                    ),
                ),
            ],
            options={
                "db_table": "policy_history",
                "ordering": ["changed_at"],
            },
        ),
    ]
